//! Item definitions using the entity_macros system
//!
//! This file consolidates:
//! - ItemSpec struct definition
//! - ItemId enum
//! - All item spec constants
//! - The spec() method on ItemId

use crate::inventory::EquipmentSlot;
use crate::stats::{StatSheet, StatType};

// Import ItemType and related enums (these are NOT generated by the macro)
pub use super::enums::{
    ConsumableType, EquipmentType, ItemQuality, ItemType, MaterialType, ToolKind,
};

entity_macros::define_entity! {
    spec ItemSpec {
        pub name: &'static str,
        pub item_type: ItemType,
        pub quality: Option<ItemQuality>,
        pub max_upgrades: i32,
        pub max_stack_quantity: u32,
        pub stats: StatSheet,
        pub gold_value: i32,
    }

    id ItemId;

    variants {
        // ─────────────────────────────────────────────────────────────────────
        // Weapons
        // ─────────────────────────────────────────────────────────────────────
        Sword {
            name: "Sword",
            item_type: ItemType::Equipment(EquipmentType::Weapon),
            quality: None,
            stats: StatSheet::new().with(StatType::Attack, 10),
            max_upgrades: 5,
            max_stack_quantity: 1,
            gold_value: 15,
        }
        Dagger {
            name: "Dagger",
            item_type: ItemType::Equipment(EquipmentType::Weapon),
            quality: None,
            stats: StatSheet::new().with(StatType::Attack, 6),
            max_upgrades: 5,
            max_stack_quantity: 1,
            gold_value: 10,
        }
        TinSword {
            name: "Tin Sword",
            item_type: ItemType::Equipment(EquipmentType::Weapon),
            quality: None,
            stats: StatSheet::new().with(StatType::Attack, 12),
            max_upgrades: 5,
            max_stack_quantity: 1,
            gold_value: 15,
        }
        CopperSword {
            name: "Copper Sword",
            item_type: ItemType::Equipment(EquipmentType::Weapon),
            quality: None,
            stats: StatSheet::new().with(StatType::Attack, 12),
            max_upgrades: 5,
            max_stack_quantity: 1,
            gold_value: 15,
        }
        BronzeSword {
            name: "Bronze Sword",
            item_type: ItemType::Equipment(EquipmentType::Weapon),
            quality: None,
            stats: StatSheet::new().with(StatType::Attack, 16),
            max_upgrades: 7,
            max_stack_quantity: 1,
            gold_value: 25,
        }
        BonkStick {
            name: "BONK STICK",
            item_type: ItemType::Equipment(EquipmentType::Weapon),
            quality: Some(ItemQuality::Mythic),
            stats: StatSheet::new().with(StatType::Attack, 100),
            max_upgrades: 99,
            max_stack_quantity: 1,
            gold_value: 25000,
        }

        // ─────────────────────────────────────────────────────────────────────
        // Shields
        // ─────────────────────────────────────────────────────────────────────
        BasicShield {
            name: "Basic Shield",
            item_type: ItemType::Equipment(EquipmentType::Shield),
            quality: None,
            stats: StatSheet::new().with(StatType::Defense, 4),
            max_upgrades: 5,
            max_stack_quantity: 1,
            gold_value: 15,
        }

        // ─────────────────────────────────────────────────────────────────────
        // Tomes
        // ─────────────────────────────────────────────────────────────────────
        ApprenticeTome {
            name: "Apprentice Tome",
            item_type: ItemType::Equipment(EquipmentType::Tome),
            quality: Some(ItemQuality::Normal),
            stats: StatSheet::new(),
            max_upgrades: 0,
            max_stack_quantity: 1,
            gold_value: 50,
        }

        // ─────────────────────────────────────────────────────────────────────
        // Copper Armor
        // ─────────────────────────────────────────────────────────────────────
        CopperHelmet {
            name: "Copper Helmet",
            item_type: ItemType::Equipment(EquipmentType::Armor(EquipmentSlot::Head)),
            quality: None,
            stats: StatSheet::new().with(StatType::Defense, 36),
            max_upgrades: 5,
            max_stack_quantity: 1,
            gold_value: 180,
        }
        CopperChestplate {
            name: "Copper Chestplate",
            item_type: ItemType::Equipment(EquipmentType::Armor(EquipmentSlot::Chest)),
            quality: None,
            stats: StatSheet::new().with(StatType::Defense, 60),
            max_upgrades: 5,
            max_stack_quantity: 1,
            gold_value: 300,
        }
        CopperGauntlets {
            name: "Copper Gauntlets",
            item_type: ItemType::Equipment(EquipmentType::Armor(EquipmentSlot::Hands)),
            quality: None,
            stats: StatSheet::new().with(StatType::Defense, 24),
            max_upgrades: 5,
            max_stack_quantity: 1,
            gold_value: 120,
        }
        CopperGreaves {
            name: "Copper Greaves",
            item_type: ItemType::Equipment(EquipmentType::Armor(EquipmentSlot::Feet)),
            quality: None,
            stats: StatSheet::new().with(StatType::Defense, 30),
            max_upgrades: 5,
            max_stack_quantity: 1,
            gold_value: 150,
        }
        CopperLeggings {
            name: "Copper Leggings",
            item_type: ItemType::Equipment(EquipmentType::Armor(EquipmentSlot::Legs)),
            quality: None,
            stats: StatSheet::new().with(StatType::Defense, 54),
            max_upgrades: 5,
            max_stack_quantity: 1,
            gold_value: 270,
        }

        // ─────────────────────────────────────────────────────────────────────
        // Tin Armor
        // ─────────────────────────────────────────────────────────────────────
        TinHelmet {
            name: "Tin Helmet",
            item_type: ItemType::Equipment(EquipmentType::Armor(EquipmentSlot::Head)),
            quality: None,
            stats: StatSheet::new().with(StatType::Defense, 36),
            max_upgrades: 5,
            max_stack_quantity: 1,
            gold_value: 180,
        }
        TinChestplate {
            name: "Tin Chestplate",
            item_type: ItemType::Equipment(EquipmentType::Armor(EquipmentSlot::Chest)),
            quality: None,
            stats: StatSheet::new().with(StatType::Defense, 60),
            max_upgrades: 5,
            max_stack_quantity: 1,
            gold_value: 300,
        }
        TinGauntlets {
            name: "Tin Gauntlets",
            item_type: ItemType::Equipment(EquipmentType::Armor(EquipmentSlot::Hands)),
            quality: None,
            stats: StatSheet::new().with(StatType::Defense, 24),
            max_upgrades: 5,
            max_stack_quantity: 1,
            gold_value: 120,
        }
        TinGreaves {
            name: "Tin Greaves",
            item_type: ItemType::Equipment(EquipmentType::Armor(EquipmentSlot::Feet)),
            quality: None,
            stats: StatSheet::new().with(StatType::Defense, 30),
            max_upgrades: 5,
            max_stack_quantity: 1,
            gold_value: 150,
        }
        TinLeggings {
            name: "Tin Leggings",
            item_type: ItemType::Equipment(EquipmentType::Armor(EquipmentSlot::Legs)),
            quality: None,
            stats: StatSheet::new().with(StatType::Defense, 54),
            max_upgrades: 5,
            max_stack_quantity: 1,
            gold_value: 270,
        }

        // ─────────────────────────────────────────────────────────────────────
        // Bronze Armor
        // ─────────────────────────────────────────────────────────────────────
        BronzeHelmet {
            name: "Bronze Helmet",
            item_type: ItemType::Equipment(EquipmentType::Armor(EquipmentSlot::Head)),
            quality: None,
            stats: StatSheet::new().with(StatType::Defense, 48),
            max_upgrades: 7,
            max_stack_quantity: 1,
            gold_value: 270,
        }
        BronzeChestplate {
            name: "Bronze Chestplate",
            item_type: ItemType::Equipment(EquipmentType::Armor(EquipmentSlot::Chest)),
            quality: None,
            stats: StatSheet::new().with(StatType::Defense, 80),
            max_upgrades: 7,
            max_stack_quantity: 1,
            gold_value: 450,
        }
        BronzeGauntlets {
            name: "Bronze Gauntlets",
            item_type: ItemType::Equipment(EquipmentType::Armor(EquipmentSlot::Hands)),
            quality: None,
            stats: StatSheet::new().with(StatType::Defense, 32),
            max_upgrades: 7,
            max_stack_quantity: 1,
            gold_value: 180,
        }
        BronzeGreaves {
            name: "Bronze Greaves",
            item_type: ItemType::Equipment(EquipmentType::Armor(EquipmentSlot::Feet)),
            quality: None,
            stats: StatSheet::new().with(StatType::Defense, 40),
            max_upgrades: 7,
            max_stack_quantity: 1,
            gold_value: 225,
        }
        BronzeLeggings {
            name: "Bronze Leggings",
            item_type: ItemType::Equipment(EquipmentType::Armor(EquipmentSlot::Legs)),
            quality: None,
            stats: StatSheet::new().with(StatType::Defense, 72),
            max_upgrades: 7,
            max_stack_quantity: 1,
            gold_value: 405,
        }

        // ─────────────────────────────────────────────────────────────────────
        // Tools
        // ─────────────────────────────────────────────────────────────────────
        BronzePickaxe {
            name: "Bronze Pickaxe",
            item_type: ItemType::Equipment(EquipmentType::Tool(ToolKind::Pickaxe)),
            quality: None,
            stats: StatSheet::new().with(StatType::Attack, 10).with(StatType::Mining, 10),
            max_upgrades: 5,
            max_stack_quantity: 1,
            gold_value: 50,
        }

        // ─────────────────────────────────────────────────────────────────────
        // Accessories
        // ─────────────────────────────────────────────────────────────────────
        GoldRing {
            name: "Midas' Touch",
            item_type: ItemType::Equipment(EquipmentType::Ring),
            quality: None,
            stats: StatSheet::new().with(StatType::GoldFind, 10),
            max_upgrades: 7,
            max_stack_quantity: 1,
            gold_value: 50,
        }
        ImbaRing {
            name: "IMBA RING",
            item_type: ItemType::Equipment(EquipmentType::Ring),
            quality: Some(ItemQuality::Normal),
            stats: StatSheet::new().with(StatType::GoldFind, 200).with(StatType::MagicFind, 200),
            max_upgrades: 99,
            max_stack_quantity: 1,
            gold_value: 25000,
        }

        // ─────────────────────────────────────────────────────────────────────
        // Ores
        // ─────────────────────────────────────────────────────────────────────
        Coal {
            name: "Coal",
            item_type: ItemType::Material(MaterialType::Ore),
            quality: Some(ItemQuality::Normal),
            stats: StatSheet::new(),
            max_upgrades: 0,
            max_stack_quantity: 99,
            gold_value: 4,
        }
        CopperOre {
            name: "Copper Ore",
            item_type: ItemType::Material(MaterialType::Ore),
            quality: Some(ItemQuality::Normal),
            stats: StatSheet::new(),
            max_upgrades: 0,
            max_stack_quantity: 99,
            gold_value: 5,
        }
        TinOre {
            name: "Tin Ore",
            item_type: ItemType::Material(MaterialType::Ore),
            quality: Some(ItemQuality::Normal),
            stats: StatSheet::new(),
            max_upgrades: 0,
            max_stack_quantity: 99,
            gold_value: 5,
        }

        // ─────────────────────────────────────────────────────────────────────
        // Ingots
        // ─────────────────────────────────────────────────────────────────────
        TinIngot {
            name: "Tin Ingot",
            item_type: ItemType::Material(MaterialType::CraftingMaterial),
            quality: Some(ItemQuality::Normal),
            stats: StatSheet::new(),
            max_upgrades: 0,
            max_stack_quantity: 99,
            gold_value: 10,
        }
        CopperIngot {
            name: "Copper Ingot",
            item_type: ItemType::Material(MaterialType::CraftingMaterial),
            quality: Some(ItemQuality::Normal),
            stats: StatSheet::new(),
            max_upgrades: 0,
            max_stack_quantity: 99,
            gold_value: 10,
        }
        BronzeIngot {
            name: "Bronze Ingot",
            item_type: ItemType::Material(MaterialType::CraftingMaterial),
            quality: Some(ItemQuality::Normal),
            stats: StatSheet::new(),
            max_upgrades: 0,
            max_stack_quantity: 99,
            gold_value: 15,
        }

        // ─────────────────────────────────────────────────────────────────────
        // Materials
        // ─────────────────────────────────────────────────────────────────────
        Cowhide {
            name: "Cowhide",
            item_type: ItemType::Material(MaterialType::CraftingMaterial),
            quality: Some(ItemQuality::Normal),
            stats: StatSheet::new(),
            max_upgrades: 0,
            max_stack_quantity: 99,
            gold_value: 4,
        }
        SlimeGel {
            name: "Slime Gel",
            item_type: ItemType::Material(MaterialType::CraftingMaterial),
            quality: Some(ItemQuality::Normal),
            stats: StatSheet::new(),
            max_upgrades: 0,
            max_stack_quantity: 99,
            gold_value: 4,
        }

        // ─────────────────────────────────────────────────────────────────────
        // Consumables
        // ─────────────────────────────────────────────────────────────────────
        BasicHPPotion {
            name: "Basic HP Potion",
            item_type: ItemType::Consumable(ConsumableType::Potion),
            quality: Some(ItemQuality::Normal),
            stats: StatSheet::new(),
            max_upgrades: 0,
            max_stack_quantity: 99,
            gold_value: 25,
        }

        // ─────────────────────────────────────────────────────────────────────
        // Upgrade Materials
        // ─────────────────────────────────────────────────────────────────────
        QualityUpgradeStone {
            name: "Magic Rock",
            item_type: ItemType::Material(MaterialType::UpgradeStone),
            quality: Some(ItemQuality::Mythic),
            stats: StatSheet::new(),
            max_upgrades: 0,
            max_stack_quantity: 99,
            gold_value: 500,
        }
    }
}

// Re-export ItemRegistry type for compatibility
pub type ItemRegistry = crate::registry::Registry<ItemId, ItemSpec>;

// ─────────────────────────────────────────────────────────────────────────────
// Spawn Implementation
// ─────────────────────────────────────────────────────────────────────────────

use uuid::Uuid;
use crate::magic::tome::Tome;
use crate::registry::{RegistryDefaults, SpawnFromSpec};
use super::definition::Item;

impl SpawnFromSpec<ItemId> for ItemSpec {
    type Output = Item;

    fn spawn_from_spec(item_id: ItemId, spec: &Self) -> Self::Output {
        // Use fixed quality from spec, or roll if None
        let quality = spec.quality.unwrap_or_else(ItemQuality::roll);
        let base_stats = spec.stats.clone();
        let stats = quality.multiply_stats(base_stats.clone());

        // Initialize tome_data if this is a tome item
        let tome_data = match spec.item_type {
            ItemType::Equipment(EquipmentType::Tome) => Some(Tome::standard()),
            _ => None,
        };

        Item {
            item_uuid: Uuid::new_v4(),
            item_id,
            item_type: spec.item_type,
            name: spec.name,
            is_equipped: false,
            is_locked: false,
            num_upgrades: 0,
            max_upgrades: spec.max_upgrades,
            max_stack_quantity: spec.max_stack_quantity,
            gold_value: spec.gold_value,
            base_stats,
            stats,
            quality,
            tome_data,
        }
    }
}

impl RegistryDefaults<ItemId> for ItemSpec {
    fn defaults() -> impl IntoIterator<Item = (ItemId, Self)> {
        ItemId::ALL.iter().map(|id| (*id, id.spec().clone()))
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Convenience Methods
// ─────────────────────────────────────────────────────────────────────────────

impl ItemId {
    /// Spawn an Item instance from this ItemId
    pub fn spawn(&self) -> Item {
        ItemSpec::spawn_from_spec(*self, self.spec())
    }
}
