//! Item definitions using the entity_macros system
//!
//! This file consolidates:
//! - ItemSpec struct definition
//! - ItemId enum
//! - All item spec constants
//! - The spec() method on ItemId

use crate::inventory::EquipmentSlot;
use crate::stats::{StatSheet, StatType};

// Import ItemType and related enums (these are NOT generated by the macro)
pub use super::enums::{
    ConsumableType, EquipmentType, ItemQuality, ItemType, MaterialType, ToolKind,
};

entity_macros::define_entity! {
    spec ItemSpec {
        pub name: String,
        pub item_type: ItemType,
        pub quality: Option<ItemQuality>,
        pub max_upgrades: i32,
        pub max_stack_quantity: u32,
        pub stats: StatSheet,
        pub gold_value: i32,
    }

    id ItemId;

    variants {
        // ─────────────────────────────────────────────────────────────────────
        // Weapons
        // ─────────────────────────────────────────────────────────────────────
        Sword {
            name: String::from("Sword"),
            item_type: ItemType::Equipment(EquipmentType::Weapon),
            quality: None,
            stats: StatSheet::new().with(StatType::Attack, 10),
            max_upgrades: 5,
            max_stack_quantity: 1,
            gold_value: 15,
        }
        Dagger {
            name: String::from("Dagger"),
            item_type: ItemType::Equipment(EquipmentType::Weapon),
            quality: None,
            stats: StatSheet::new().with(StatType::Attack, 6),
            max_upgrades: 5,
            max_stack_quantity: 1,
            gold_value: 10,
        }
        GoldSword {
            name: String::from("Gold Sword"),
            item_type: ItemType::Equipment(EquipmentType::Weapon),
            quality: None,
            stats: StatSheet::new().with(StatType::Attack, 12),
            max_upgrades: 5,
            max_stack_quantity: 1,
            gold_value: 15,
        }
        IronSword {
            name: String::from("Iron Sword"),
            item_type: ItemType::Equipment(EquipmentType::Weapon),
            quality: None,
            stats: StatSheet::new().with(StatType::Attack, 12),
            max_upgrades: 5,
            max_stack_quantity: 1,
            gold_value: 15,
        }
        CopperSword {
            name: String::from("Copper Sword"),
            item_type: ItemType::Equipment(EquipmentType::Weapon),
            quality: None,
            stats: StatSheet::new().with(StatType::Attack, 16),
            max_upgrades: 7,
            max_stack_quantity: 1,
            gold_value: 25,
        }
        BonkStick {
            name: String::from("BONK STICK"),
            item_type: ItemType::Equipment(EquipmentType::Weapon),
            quality: Some(ItemQuality::Mythic),
            stats: StatSheet::new().with(StatType::Attack, 100),
            max_upgrades: 99,
            max_stack_quantity: 1,
            gold_value: 25000,
        }

        // ─────────────────────────────────────────────────────────────────────
        // Shields
        // ─────────────────────────────────────────────────────────────────────
        BasicShield {
            name: String::from("Basic Shield"),
            item_type: ItemType::Equipment(EquipmentType::Shield),
            quality: None,
            stats: StatSheet::new().with(StatType::Defense, 4),
            max_upgrades: 5,
            max_stack_quantity: 1,
            gold_value: 15,
        }

        // ─────────────────────────────────────────────────────────────────────
        // Iron Armor
        // ─────────────────────────────────────────────────────────────────────
        IronHelmet {
            name: String::from("Iron Helmet"),
            item_type: ItemType::Equipment(EquipmentType::Armor(EquipmentSlot::Head)),
            quality: None,
            stats: StatSheet::new().with(StatType::Defense, 36),
            max_upgrades: 5,
            max_stack_quantity: 1,
            gold_value: 180,
        }
        IronChestplate {
            name: String::from("Iron Chestplate"),
            item_type: ItemType::Equipment(EquipmentType::Armor(EquipmentSlot::Chest)),
            quality: None,
            stats: StatSheet::new().with(StatType::Defense, 60),
            max_upgrades: 5,
            max_stack_quantity: 1,
            gold_value: 300,
        }
        IronGauntlets {
            name: String::from("Iron Gauntlets"),
            item_type: ItemType::Equipment(EquipmentType::Armor(EquipmentSlot::Hands)),
            quality: None,
            stats: StatSheet::new().with(StatType::Defense, 24),
            max_upgrades: 5,
            max_stack_quantity: 1,
            gold_value: 120,
        }
        IronGreaves {
            name: String::from("Iron Greaves"),
            item_type: ItemType::Equipment(EquipmentType::Armor(EquipmentSlot::Feet)),
            quality: None,
            stats: StatSheet::new().with(StatType::Defense, 30),
            max_upgrades: 5,
            max_stack_quantity: 1,
            gold_value: 150,
        }
        IronLeggings {
            name: String::from("Iron Leggings"),
            item_type: ItemType::Equipment(EquipmentType::Armor(EquipmentSlot::Legs)),
            quality: None,
            stats: StatSheet::new().with(StatType::Defense, 54),
            max_upgrades: 5,
            max_stack_quantity: 1,
            gold_value: 270,
        }

        // ─────────────────────────────────────────────────────────────────────
        // Gold Armor
        // ─────────────────────────────────────────────────────────────────────
        GoldHelmet {
            name: String::from("Gold Helmet"),
            item_type: ItemType::Equipment(EquipmentType::Armor(EquipmentSlot::Head)),
            quality: None,
            stats: StatSheet::new().with(StatType::Defense, 36),
            max_upgrades: 5,
            max_stack_quantity: 1,
            gold_value: 180,
        }
        GoldChestplate {
            name: String::from("Gold Chestplate"),
            item_type: ItemType::Equipment(EquipmentType::Armor(EquipmentSlot::Chest)),
            quality: None,
            stats: StatSheet::new().with(StatType::Defense, 60),
            max_upgrades: 5,
            max_stack_quantity: 1,
            gold_value: 300,
        }
        GoldGauntlets {
            name: String::from("Gold Gauntlets"),
            item_type: ItemType::Equipment(EquipmentType::Armor(EquipmentSlot::Hands)),
            quality: None,
            stats: StatSheet::new().with(StatType::Defense, 24),
            max_upgrades: 5,
            max_stack_quantity: 1,
            gold_value: 120,
        }
        GoldGreaves {
            name: String::from("Gold Greaves"),
            item_type: ItemType::Equipment(EquipmentType::Armor(EquipmentSlot::Feet)),
            quality: None,
            stats: StatSheet::new().with(StatType::Defense, 30),
            max_upgrades: 5,
            max_stack_quantity: 1,
            gold_value: 150,
        }
        GoldLeggings {
            name: String::from("Gold Leggings"),
            item_type: ItemType::Equipment(EquipmentType::Armor(EquipmentSlot::Legs)),
            quality: None,
            stats: StatSheet::new().with(StatType::Defense, 54),
            max_upgrades: 5,
            max_stack_quantity: 1,
            gold_value: 270,
        }

        // ─────────────────────────────────────────────────────────────────────
        // Copper Armor
        // ─────────────────────────────────────────────────────────────────────
        CopperHelmet {
            name: String::from("Copper Helmet"),
            item_type: ItemType::Equipment(EquipmentType::Armor(EquipmentSlot::Head)),
            quality: None,
            stats: StatSheet::new().with(StatType::Defense, 48),
            max_upgrades: 7,
            max_stack_quantity: 1,
            gold_value: 270,
        }
        CopperChestplate {
            name: String::from("Copper Chestplate"),
            item_type: ItemType::Equipment(EquipmentType::Armor(EquipmentSlot::Chest)),
            quality: None,
            stats: StatSheet::new().with(StatType::Defense, 80),
            max_upgrades: 7,
            max_stack_quantity: 1,
            gold_value: 450,
        }
        CopperGauntlets {
            name: String::from("Copper Gauntlets"),
            item_type: ItemType::Equipment(EquipmentType::Armor(EquipmentSlot::Hands)),
            quality: None,
            stats: StatSheet::new().with(StatType::Defense, 32),
            max_upgrades: 7,
            max_stack_quantity: 1,
            gold_value: 180,
        }
        CopperGreaves {
            name: String::from("Copper Greaves"),
            item_type: ItemType::Equipment(EquipmentType::Armor(EquipmentSlot::Feet)),
            quality: None,
            stats: StatSheet::new().with(StatType::Defense, 40),
            max_upgrades: 7,
            max_stack_quantity: 1,
            gold_value: 225,
        }
        CopperLeggings {
            name: String::from("Copper Leggings"),
            item_type: ItemType::Equipment(EquipmentType::Armor(EquipmentSlot::Legs)),
            quality: None,
            stats: StatSheet::new().with(StatType::Defense, 72),
            max_upgrades: 7,
            max_stack_quantity: 1,
            gold_value: 405,
        }

        // ─────────────────────────────────────────────────────────────────────
        // Tools
        // ─────────────────────────────────────────────────────────────────────
        CopperPickaxe {
            name: String::from("Copper Pickaxe"),
            item_type: ItemType::Equipment(EquipmentType::Tool(ToolKind::Pickaxe)),
            quality: None,
            stats: StatSheet::new().with(StatType::Attack, 10).with(StatType::Mining, 10),
            max_upgrades: 5,
            max_stack_quantity: 1,
            gold_value: 50,
        }

        // ─────────────────────────────────────────────────────────────────────
        // Accessories
        // ─────────────────────────────────────────────────────────────────────
        GoldRing {
            name: String::from("Midas' Touch"),
            item_type: ItemType::Equipment(EquipmentType::Ring),
            quality: None,
            stats: StatSheet::new().with(StatType::GoldFind, 10),
            max_upgrades: 7,
            max_stack_quantity: 1,
            gold_value: 50,
        }
        ImbaRing {
            name: String::from("IMBA RING"),
            item_type: ItemType::Equipment(EquipmentType::Ring),
            quality: Some(ItemQuality::Normal),
            stats: StatSheet::new().with(StatType::GoldFind, 200).with(StatType::MagicFind, 200),
            max_upgrades: 99,
            max_stack_quantity: 1,
            gold_value: 25000,
        }

        // ─────────────────────────────────────────────────────────────────────
        // Ores
        // ─────────────────────────────────────────────────────────────────────
        Coal {
            name: String::from("Coal"),
            item_type: ItemType::Material(MaterialType::Ore),
            quality: Some(ItemQuality::Normal),
            stats: StatSheet::new(),
            max_upgrades: 0,
            max_stack_quantity: 99,
            gold_value: 4,
        }
        IronOre {
            name: String::from("Iron Ore"),
            item_type: ItemType::Material(MaterialType::Ore),
            quality: Some(ItemQuality::Normal),
            stats: StatSheet::new(),
            max_upgrades: 0,
            max_stack_quantity: 99,
            gold_value: 5,
        }
        GoldOre {
            name: String::from("Gold Ore"),
            item_type: ItemType::Material(MaterialType::Ore),
            quality: Some(ItemQuality::Normal),
            stats: StatSheet::new(),
            max_upgrades: 0,
            max_stack_quantity: 99,
            gold_value: 5,
        }

        // ─────────────────────────────────────────────────────────────────────
        // Ingots
        // ─────────────────────────────────────────────────────────────────────
        GoldIngot {
            name: String::from("Gold Ingot"),
            item_type: ItemType::Material(MaterialType::CraftingMaterial),
            quality: Some(ItemQuality::Normal),
            stats: StatSheet::new(),
            max_upgrades: 0,
            max_stack_quantity: 99,
            gold_value: 10,
        }
        IronIngot {
            name: String::from("Iron Ingot"),
            item_type: ItemType::Material(MaterialType::CraftingMaterial),
            quality: Some(ItemQuality::Normal),
            stats: StatSheet::new(),
            max_upgrades: 0,
            max_stack_quantity: 99,
            gold_value: 10,
        }
        CopperIngot {
            name: String::from("Copper Ingot"),
            item_type: ItemType::Material(MaterialType::CraftingMaterial),
            quality: Some(ItemQuality::Normal),
            stats: StatSheet::new(),
            max_upgrades: 0,
            max_stack_quantity: 99,
            gold_value: 15,
        }

        // ─────────────────────────────────────────────────────────────────────
        // Materials
        // ─────────────────────────────────────────────────────────────────────
        Cowhide {
            name: String::from("Cowhide"),
            item_type: ItemType::Material(MaterialType::CraftingMaterial),
            quality: Some(ItemQuality::Normal),
            stats: StatSheet::new(),
            max_upgrades: 0,
            max_stack_quantity: 99,
            gold_value: 4,
        }
        SlimeGel {
            name: String::from("Slime Gel"),
            item_type: ItemType::Material(MaterialType::CraftingMaterial),
            quality: Some(ItemQuality::Normal),
            stats: StatSheet::new(),
            max_upgrades: 0,
            max_stack_quantity: 99,
            gold_value: 4,
        }

        // ─────────────────────────────────────────────────────────────────────
        // Consumables
        // ─────────────────────────────────────────────────────────────────────
        BasicHPPotion {
            name: String::from("Basic HP Potion"),
            item_type: ItemType::Consumable(ConsumableType::Potion),
            quality: Some(ItemQuality::Normal),
            stats: StatSheet::new(),
            max_upgrades: 0,
            max_stack_quantity: 99,
            gold_value: 25,
        }

        // ─────────────────────────────────────────────────────────────────────
        // Upgrade Materials
        // ─────────────────────────────────────────────────────────────────────
        QualityUpgradeStone {
            name: String::from("Magic Rock"),
            item_type: ItemType::Material(MaterialType::UpgradeStone),
            quality: Some(ItemQuality::Mythic),
            stats: StatSheet::new(),
            max_upgrades: 0,
            max_stack_quantity: 99,
            gold_value: 500,
        }
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Spawn Implementation
// ─────────────────────────────────────────────────────────────────────────────

use uuid::Uuid;
use crate::registry::{RegistryDefaults, SpawnFromSpec};
use super::definition::Item;

impl SpawnFromSpec<ItemId> for ItemSpec {
    type Output = Item;

    fn spawn_from_spec(item_id: ItemId, spec: &Self) -> Self::Output {
        spec.spawn(item_id)
    }
}

impl ItemSpec {
    /// Spawn an Item from this spec with the given ItemId. Internal use only.
    fn spawn(&self, id: ItemId) -> Item {
        // Use fixed quality from spec, or roll if None
        let quality = self.quality.unwrap_or_else(ItemQuality::roll);
        let base_stats = self.stats.clone();
        let stats = quality.multiply_stats(&base_stats);

        Item {
            item_uuid: Uuid::new_v4(),
            item_id: id,
            item_type: self.item_type,
            name: self.name.clone(),
            is_equipped: false,
            is_locked: false,
            num_upgrades: 0,
            max_upgrades: self.max_upgrades,
            max_stack_quantity: self.max_stack_quantity,
            gold_value: self.gold_value,
            base_stats,
            stats,
            quality,
        }
    }

    /// Create a scaled copy of this spec with stats multiplied by the given factor.
    /// Useful for dungeon scaling, elite variants, etc.
    pub fn with_multiplier(&self, multiplier: f32) -> ItemSpec {
        let mut scaled_stats = crate::stats::StatSheet::new();
        for stat_type in crate::stats::StatType::all() {
            let value = self.stats.value(*stat_type);
            if value > 0 {
                let new_value = (value as f32 * multiplier).round() as i32;
                scaled_stats.insert(stat_type.instance(new_value));
            }
        }

        ItemSpec {
            name: self.name.clone(),
            item_type: self.item_type,
            quality: self.quality,
            max_upgrades: self.max_upgrades,
            max_stack_quantity: self.max_stack_quantity,
            stats: scaled_stats,
            gold_value: (self.gold_value as f32 * multiplier).round() as i32,
        }
    }

    /// Create a copy with a new name (e.g., for "Enchanted Sword").
    pub fn with_name(&self, name: impl Into<String>) -> ItemSpec {
        ItemSpec {
            name: name.into(),
            item_type: self.item_type,
            quality: self.quality,
            max_upgrades: self.max_upgrades,
            max_stack_quantity: self.max_stack_quantity,
            stats: self.stats.clone(),
            gold_value: self.gold_value,
        }
    }

    /// Create a copy with a fixed quality.
    pub fn with_quality(&self, quality: ItemQuality) -> ItemSpec {
        ItemSpec {
            name: self.name.clone(),
            item_type: self.item_type,
            quality: Some(quality),
            max_upgrades: self.max_upgrades,
            max_stack_quantity: self.max_stack_quantity,
            stats: self.stats.clone(),
            gold_value: self.gold_value,
        }
    }
}

impl RegistryDefaults<ItemId> for ItemSpec {
    fn defaults() -> impl IntoIterator<Item = (ItemId, Self)> {
        ItemId::ALL.iter().map(|id| (*id, id.spec().clone()))
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Spawning
// ─────────────────────────────────────────────────────────────────────────────

/// Builder for spawning modified items.
pub struct ItemSpawner {
    id: ItemId,
    spec: ItemSpec,
}

impl ItemSpawner {
    /// Spawn the item with all modifications applied.
    pub fn spawn(self) -> Item {
        self.spec.spawn(self.id)
    }

    /// Scale all stat values and gold by a multiplier.
    pub fn with_multiplier(mut self, multiplier: f32) -> Self {
        self.spec = self.spec.with_multiplier(multiplier);
        self
    }

    /// Change the item's display name.
    pub fn with_name(mut self, name: impl Into<String>) -> Self {
        self.spec = self.spec.with_name(name);
        self
    }

    /// Set the item's quality.
    pub fn with_quality(mut self, quality: ItemQuality) -> Self {
        self.spec = self.spec.with_quality(quality);
        self
    }
}

impl ItemId {
    /// Spawn an Item instance from this ItemId.
    pub fn spawn(&self) -> Item {
        self.spec().spawn(*self)
    }

    /// Scale all stat values and gold by a multiplier.
    pub fn with_multiplier(&self, multiplier: f32) -> ItemSpawner {
        ItemSpawner {
            id: *self,
            spec: self.spec().with_multiplier(multiplier),
        }
    }

    /// Change the item's display name.
    pub fn with_name(&self, name: impl Into<String>) -> ItemSpawner {
        ItemSpawner {
            id: *self,
            spec: self.spec().with_name(name),
        }
    }

    /// Set the item's quality.
    pub fn with_quality(&self, quality: ItemQuality) -> ItemSpawner {
        ItemSpawner {
            id: *self,
            spec: self.spec().with_quality(quality),
        }
    }

    /// Get the sprite sheet key for this item's icon.
    pub fn sprite_sheet_key(&self) -> crate::assets::SpriteSheetKey {
        use crate::assets::SpriteSheetKey;
        match self {
            ItemId::GoldSword => SpriteSheetKey::GoldSword,
            ItemId::IronSword => SpriteSheetKey::IronSword,
            ItemId::CopperSword => SpriteSheetKey::CopperSword,
            // Ores, ingots, and materials from crafting sheet
            ItemId::IronOre
            | ItemId::GoldOre
            | ItemId::IronIngot
            | ItemId::GoldIngot
            | ItemId::CopperIngot
            | ItemId::Cowhide => SpriteSheetKey::CraftingMaterials,
            _ => SpriteSheetKey::IconItems,
        }
    }

    /// Get the sprite slice name for this item in the IconItems sprite sheet.
    pub fn sprite_name(&self) -> &'static str {
        match self {
            // Consumables
            ItemId::BasicHPPotion => "Slice_337",
            // Weapons
            ItemId::Sword => "Slice_155",
            ItemId::Dagger => "Slice_156",
            ItemId::GoldSword => "gold_sword",
            ItemId::IronSword => "iron_sword",
            ItemId::CopperSword => "copper_sword",
            ItemId::BonkStick => "Slice_607",
            // Shields
            ItemId::BasicShield => "Slice_100",
            // Helmets
            ItemId::IronHelmet => "Slice_101",
            ItemId::GoldHelmet => "Slice_108",
            ItemId::CopperHelmet => "Slice_108",
            // Chestplates
            ItemId::IronChestplate => "Slice_551",
            ItemId::GoldChestplate => "Slice_551",
            ItemId::CopperChestplate => "Slice_551",
            // Gauntlets
            ItemId::IronGauntlets => "Slice_558",
            ItemId::GoldGauntlets => "Slice_558",
            ItemId::CopperGauntlets => "Slice_558",
            // Greaves
            ItemId::IronGreaves => "Slice_367",
            ItemId::GoldGreaves => "Slice_367",
            ItemId::CopperGreaves => "Slice_367",
            // Leggings
            ItemId::IronLeggings => "Slice_42",
            ItemId::GoldLeggings => "Slice_42",
            ItemId::CopperLeggings => "Slice_42",
            // Tools
            ItemId::CopperPickaxe => "Slice_826",
            // Accessories
            ItemId::GoldRing => "Slice_50",
            ItemId::ImbaRing => "Slice_1009",
            // Ores
            ItemId::Coal => "Slice_693",
            ItemId::IronOre => "iron_ore",
            ItemId::GoldOre => "gold_ore",
            // Ingots
            ItemId::IronIngot => "iron_ingot",
            ItemId::CopperIngot => "copper_ingot",
            ItemId::GoldIngot => "gold_ingot",
            // Materials
            ItemId::Cowhide => "leather",
            ItemId::SlimeGel => "Slice_952",
            // Upgrade Materials
            ItemId::QualityUpgradeStone => "Slice_57",
        }
    }
}
