pub(crate) mod field;
pub(crate) mod location;
pub(crate) mod loot;
pub(crate) mod town;
pub(crate) mod blacksmith;
pub(crate) mod entities;
pub(crate) mod combat;
pub(crate) mod item;
pub(crate) mod registry;
pub(crate) mod inventory;
pub(crate) mod utilities;
pub(crate) mod stats;
pub(crate) mod store;
pub(crate) mod ui;
pub(crate) mod system;
pub(crate) mod mine;
// Re-exports for main.rs
pub use inventory::{EquipmentSlot, HasInventory};
pub use item::ItemId;
pub use system::{game_state, init_game_state, GameState};
pub use ui::Id;
